### ISSUE TITLE
Publication author list not match author order in bib

### ISSUE THREAD

**Issue by tang-kevin** [hhuslamlab/website#182]
Publication author list not match author order in bib or simply do not match the list in author field in the bib
e.g., https://slam.phil.hhu.de/publication/dockumgender/
e.g., https://slam.phil.hhu.de/publication/tang-2020-verhicle-interaction/

**Comment by xuanxuanx-98** [comment]
should I simply align the order of the authors on the website to the orders in the .bib? Because to my knowledge our lab members' names should be shown first on the website itself.

**Comment by tang-kevin** [comment]
The order of the authors for each publication should match those to the orders in the bib.
Perhaps I do not understand the question.

**Comment by tang-kevin** [comment]
"Because to my knowledge our lab members' names should be shown first on the website itself."
>> Interesting. I wasn't aware of this. What was the motivation?

**Comment by xuanxuanx-98** [comment]
> "Because to my knowledge our lab members' names should be shown first on the website itself."
> 
> > > Interesting. I wasn't aware of this. What was the motivation?

probably to make it clear that the paper is relevant for the lab? I'm not quite sure about this. But if you want to change it I can go through all the publications to make sure the orders are consistent

**Comment by tang-kevin** [comment]
Thank you. I'm leaning towards just using the bib order.
Can this process be automatic?

**Comment by xuanxuanx-98** [comment]
not really. Especially considering that the author names in the bib are formatted quite differently depending on the paper :/

**Comment by tang-kevin** [comment]
I see. Then I have the following suggestion:
1) Use AI to help you struggle the author list from bib to the version in the textfield. ('This is a bib entry, extract author names in the same order but list First Name then Last Name')
2) Format the extracted author name list such that the lab members are in bold.

**Comment by xuanxuanx-98** [comment]
since the names are already in the list. I can just re-arrange those. It shouldn't take a long time.

**Comment by tang-kevin** [comment]
Go for it. Note that there are some incorrect entries.
