### ISSUE TITLE
Add Twitter Widget

### ISSUE THREAD

**Issue by tang-kevin** [hhuslamlab/website#20]
https://twitter.com/SLaMLab_HHU

Here is something that I used for the widget on my kevintang.org site.
<a class="twitter-timeline"  height="450" data-dnt="true" href="https://twitter.com/tang_kevin"  data-widget-id="463262752107003904">Tweets by @tang_kevin</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by akki2825** [comment]
stale. we have parked the issue for now.
