### ISSUE TITLE
Update classes on website

### ISSUE THREAD

**Issue by tang-kevin** [hhuslamlab/website#27]
Update the classes page and the featured classes on the front page with the Winter courses
https://slam.phil.hhu.de/classes/

Phonetics/Phonology (Intermediate)
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=232675&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung
Note: another version of this course is taught by Eoin O'Reilly (Mo 14:30-16:00) (https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=232409&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung)

Computational Modelling (Advanced):
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=233690&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung

Introduction to Corpus Phonetics  (Masters, open also to advanced BA):
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=233660&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung

Quantitative Methods for Linguistic Data: An Introduction to Statistics using R (Masters, open also to advanced BA):
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=233658&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung

Laboratory Phonology (Methode)
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=232451&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung

Language technology for Linguists with Internet of Things (IoT) (Methode)
https://lsf.hhu.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=231180&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung

**Comment by tang-kevin** [comment]
I see that Akhilesh's towards a career course has disappeared. Please reinsert it, if it was left out by accident.

**Comment by ansost** [comment]
Its still there, its just in `see all courses`. Since its not in this semester, ts not in the promoted seminars anymore.

**Comment by tang-kevin** [comment]
I cannot see it under all courses. Could you share a few lines that I can search with?

**Comment by ansost** [comment]
It is on the second page of all classes.

**Comment by tang-kevin** [comment]
I see! I wouldn't be able to find that button that easily. Would it make sense to remove the description on the all classes page to have all courses on the same page, since they each would lead to a more detailed page already?
