### ISSUE TITLE
Lab news: PnP (Chris's presentation)

### ISSUE THREAD

**Issue by tang-kevin** [hhuslamlab/website#57]
Lab news: PnP (Chris's presentation)

@cageissler : please provide detail.

**Comment by cageissler** [comment]
Not sure how much needs to be said. Something just like: 

Chris Geissler presented a poster at the 18th Phonetik und Phonologie im deutschsprachigen Raum (P&P) Conference in Bielefeld on 06.10.2022. The poster, "From Gestural Landmarks to Analysis-by-Synthesis: Tone-driven Gestural Timing in Tibetan" uses articulatory synthesis to study relative timing of speech gestures. 

You can provide a link to the OSF repository, which includes the poster and the abstract. I've also attached the poster and abstract. https://osf.io/be846/


[PundP_2022_poster_Geissler.pdf](https://github.com/hhuslamlab/website/files/9766630/PundP_2022_poster_Geissler.pdf)
[PundP_2022_submitted.pdf](https://github.com/hhuslamlab/website/files/9766631/PundP_2022_submitted.pdf)

**Comment by nemas101** [comment]
added on website
