### ISSUE TITLE
Project section

### ISSUE THREAD

**Issue by tang-kevin** [hhuslamlab/website#66]
I'd like to add one dedicated project page per project.
Currently, I'd like to particularly feature the NVidia education project, and the E-learning project. Please contact the corresponding team for information.

E-learning:
@cageissler  @julikaweber Lara

NVidia:
@akki2825

**Comment by ansost** [comment]
https://codingnconcepts.com/hugo/nested-menu-hugo/

**Comment by ansost** [comment]
AKK and I agree that the menu bar is getting too crowded, so we think we should make the menu a dropdown menu.
I propose to partition it in:

**Comment by ansost** [comment]
![image](https://user-images.githubusercontent.com/89185768/196885652-a9ac2315-42db-4e67-a5c7-b6b2f88241b9.png)
This is what this menu could look like. Toughts @tang-kevin, @akki2825 ?

**Comment by tang-kevin** [comment]
That would work well. I really like this site with the side menu but also the scroll to explore figure -- what do the professionals think here? 
https://hector-fellow-academy.de/en/

**Comment by cageissler** [comment]
The Hector Fellow site is optimized for mobile (scrolling, the little
three-line thing to open the menu). I don't know how easy/difficult that is
to implement.

Personally, I despise those websites on aesthetic grounds. Then again, I'm
a dinosaur and generally only look at work-related websites from an actual
computer, not a mobile device. Others preferences may vary.

Best,
Chris

**Comment by tang-kevin** [comment]
Do we have contents for these subproject pages yet?

**Comment by nemas101** [comment]
has been added
