### ISSUE TITLE
HOW TO INSTALL JUPYTER NOTEBOOK ON UBUNTU?

### ISSUE THREAD

**Issue by BraveMoneyLute** [hhuslamlab/website#82]
Nele has tried to install JupyterNotebook but the normal `pip install` command doesn't work
What has worked for her instead are 
``` shell= 
sudo apt install epiphany jupyter-notebook
```
```shell=
sudo apt install jupyter-notebook
```
```shell=
sudo apt install python3-notebook jupyter jupyter-core python-ipykernel 
```
She will send you the exact error message.
Source: https://askubuntu.com/questions/737094/jupyter-notebook-installation

**Comment by akki2825** [comment]
please ask them to refer this: https://docs.slam.phil.hhu.de/#/wsl?id=installing-jupyter-notebook

**Comment by BraveMoneyLute** [comment]
No, this did not work, which is why I noted it down for future references.
