### ISSUE TITLE
Aeneas Tutorial problem?

### ISSUE THREAD

**Issue by BraveMoneyLute** [hhuslamlab/website#95]
When following the detailed Installation, upon doing the last step
```
sudo python3 -m aeneas.diagnostics
```
It tells me that .cdtw, .cmfcc,  and .cew are not available.

![image](https://user-images.githubusercontent.com/104856882/207052003-f8dbff3d-6cf7-4861-8e44-5f58af908e21.png)

How do I get these?

Prof T said he found a solution to this and used it in his [CoLab file](https://colab.research.google.com/drive/1HxGohU1XgbM64RFbRv0OentoCUym0jkv?usp=sharing#scrollTo=MQznvUgnj2uh), but I'm not able to remember what he told me because someone started talking to me ;;;;;;

**Comment by tang-kevin** [comment]
The following worked for me: do these before installing anything:
sudo apt install espeak
sudo apt-get install libespeak-dev

**Comment by tang-kevin** [comment]
@akki2825

**Comment by akki2825** [comment]
did you perform all the actions mentioned in the detailed installation: https://docs.slam.phil.hhu.de/#/aeneas?id=detailed-installation ?

**Comment by BraveMoneyLute** [comment]
I forgot to close this, I followed the detailed installations but there was a section that was not backsticked and I overlooked it.

I ran all of the commands again as described in the guide and it works!

I have added the backsticks into the guide and a screenshot to let people know what they are supposed to see after the last step.
